Feature: Mini agents.md summarization
  When the user accepts the over-budget prompt, mini generates a bounded
  summary of the source instruction file, persists it at .pi/mini/agents.md
  with a SummaryRecord, and injects the summary in place of the source into
  MINI_SYSTEM_PROMPT. The summary must preserve operational facts: commands,
  conventions, forbidden actions, and verification steps.

  Background:
    Given the mini context budget policy is the default policy
    And the repo root has an AGENTS.md estimated over 1000 tokens
    And the user was prompted and chose "summarize now"

Scenario: Summary is generated by the tiny model with a bounded extraction prompt
    When the summary is generated for the over-budget file
    Then the tiny model receives the bounded extraction prompt and the source text
    And the summary is written to ".pi/mini/agents.md"
    And a SummaryRecord is stored with sourcePath, sourceMtimeMs, sourceHash, summaryPath, createdAt, and createdBy "mini"

Scenario: Very large sources fall back to the worker
    Given the source file is estimated at 20000 tokens or more
    When the summary is generated
    Then the generation is delegated via delegate_to_worker
    And the SummaryRecord createdBy is "worker"

Scenario Outline: The summary must preserve operational facts
    Given the source file contains the canary fact "<fact>"
    When the summary is generated
    Then the summary at ".pi/mini/agents.md" retains "<fact>" case-insensitively

    Examples:
      | fact                                   |
      | always run npm test before commit      |
      | never edit delegate.ts                 |
      | tests live in tests/unit               |
      | use pnpm not npm                       |
      | verify with npm run lint               |

Scenario: Quality bar is enforced before injection
    Given a summary has been generated
    When the quality gate runs
    Then the summary's estimated tokens are at most 1000
    And the keyword retention checks pass for commands, conventions, forbidden actions, and verification steps
    And only then is the summary used in place of the source in the mini instruction block

Scenario: Declining the prompt omits the file instead of overflowing
    Given the user was prompted and chose "decline"
    When the context budget is resolved
    Then the file verdict is "declined-truncated"
    And the full source file is NOT injected into mini context
    And the mini instruction block contains no content from that file

Scenario: Kill switch and reload still apply
    Given pi was started with "--no-context-files"
    When the context budget is evaluated
    Then no instruction file is injected regardless of verdict
